// Electronic Library catalogue. Loaded automatically by index.html.
// Generated by the app — edit through the UI and press Save.
window.LIBRARY_DATA = {
  "books": [
    {
      "id": "1",
      "title": "Sample Notes",
      "author": "A. Author",
      "year": "2024",
      "description": "Demo entry so you can see a card with a cover, and try Read/Download.",
      "category": "Technical",
      "fileName": "sample-notes.txt",
      "filePath": "books/sample-notes.txt",
      "thumbnail": "thumbnails/sample-notes.svg",
      "dateAdded": "2026-07-27"
    },
    {
      "id": "2",
      "title": "Sample Handbook",
      "author": "B. Writer",
      "year": "2019",
      "description": "Second demo entry, in another category and year.",
      "category": "Non-Fiction",
      "fileName": "sample-handbook.txt",
      "filePath": "books/sample-handbook.txt",
      "thumbnail": "thumbnails/sample-handbook.svg",
      "dateAdded": "2026-07-27"
    },
    {
      "id": "1785768405728",
      "title": "Персональный аналоговый компьютер",
      "author": "Алексаков Г.Н.",
      "year": "1992",
      "description": "descr1",
      "category": "Technical",
      "fileName": "Алексаков Г.Н. и др. - Персональный аналоговый компьютер - 1992.djvu",
      "filePath": "books/Алексаков Г.Н. и др. - Персональный аналоговый компьютер - 1992.djvu",
      "thumbnail": "thumbnails/270381159.0.jpg",
      "dateAdded": "2026-08-03"
    },
    {
      "id": "1785774844905",
      "title": "Book 1_11",
      "author": "autor1",
      "year": "1650",
      "description": "",
      "category": "Non-Fiction",
      "fileName": "chesnokov_va_i_dr_vyrashchivanie_rastenii_bez_pochvy.pdf",
      "filePath": "books/chesnokov_va_i_dr_vyrashchivanie_rastenii_bez_pochvy.pdf",
      "thumbnail": "thumbnails/rastenia_bez_pochvi.png",
      "dateAdded": "2026-08-03"
    }
  ],
  "categories": [
    "Fiction",
    "Non-Fiction",
    "Technical"
  ],
  "favorites": [
    "1"
  ],
  "readLater": [],
  "workBooks": [],
  "hobbyBooks": [],
  "settings": {
    "viewMode": "grid",
    "theme": "dark"
  }
};
