// Electronic Library catalogue. Loaded automatically by index.html.
// Generated by the app — edit through the UI and press Save.
window.LIBRARY_DATA = {
  "books": [
    {
      "id": "1",
      "title": "Sample Notes",
      "author": "A. Author",
      "year": "2024",
      "description": "Demo entry so you can see a card with a cover, and try Read/Download.",
      "category": "Technical",
      "fileName": "sample-notes.txt",
      "filePath": "books/sample-notes.txt",
      "thumbnail": "thumbnails/sample-notes.svg",
      "dateAdded": "2026-07-27"
    },
    {
      "id": "2",
      "title": "Sample Handbook",
      "author": "B. Writer",
      "year": "2019",
      "description": "Second demo entry, in another category and year.",
      "category": "Non-Fiction",
      "fileName": "sample-handbook.txt",
      "filePath": "books/sample-handbook.txt",
      "thumbnail": "thumbnails/sample-handbook.svg",
      "dateAdded": "2026-07-27"
    }
  ],
  "categories": [
    "Fiction",
    "Non-Fiction",
    "Technical"
  ],
  "favorites": [
    "1"
  ],
  "readLater": [],
  "workBooks": [],
  "hobbyBooks": [],
  "settings": {
    "viewMode": "grid",
    "theme": "light"
  }
};
